version: "2"

run:
  go: "1.25"
  timeout: 5m

linters:
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  enable:
    - godoclint
    - unparam
    - exhaustive
    - prealloc
    - errorlint
    - perfsprint
    - unconvert
    - wastedassign
    - gocritic
    - predeclared
    - nilerr
    - usetesting
    - nolintlint
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
