version: "2"

run:
  go: "1.26"
  timeout: 5m

linters:
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  enable:
    - godoclint
    - unparam
    - exhaustive
    - prealloc
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
